# Generated by Django 3.2.4 on 2021-06-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210617_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
